substitutions:
  icon_font: icon_font
  text_font: cn_font
  button_on_color: "0xFF8C00"            # 按钮激活状态的背景色（橙色）
  button_text_color: "0xFFFFFF"          # 按钮文字颜色（白色）
  button_control_color: "0x313131"       # 控制类按钮的默认背景色（深灰色）
  button_webhook_color: "0x212121"       # Webhook 类按钮的背景色（更深的灰色）
  button_height_single: 25px             # 单行按钮的高度
  button_width: 30px                     # 按钮的宽度
  padding: 2px                           # 按钮内边距（文字与边框的距离）
  radius: 2px                            # 按钮圆角半径
  slider_background_color: "0x505050"    # 滑块轨道的背景色
  slider_active_color: "0x2D2D2D"        # 滑块已激活部分的颜色（如进度条）
  slider_knob_color: "0xE5E5E5"          # 滑块拖动圆钮的颜色（浅灰色）

lvgl:
  style_definitions:
    # webhook样式
    - id: webhook
      bg_color: $button_webhook_color

    - id: control
      bg_color: $button_control_color
      
  theme:
    button:
      text_font: $text_font
      scroll_on_focus: false             # 聚焦时是否允许滚动（关闭）
      radius: $radius
      width: $button_width
      height: $button_height_single
      pad_all: $padding
      shadow_width: 0                    # 禁用阴影
      text_color: $button_text_color
      checked:
        bg_color: $button_on_color
        text_color: $button_text_color
