# materialdesignicons-webfont.ttf

# 图标字体
font:
  - file: "../fonts/materialdesignicons-webfont.ttf"
    id: icon_font
    size: 40
    bpp: 4
    glyphs: [
      "\U000F0335",  # mdi-灯泡
      "\U000F1A4C",  # mdi-夜灯
      "\U000F1087",  # mdi-路由器网络
      "\U000F0614",  # mdi-应用程序轮廓
      "\U000F0141",  # mdi-向左箭头
      "\U000F0143",  # mdi-向上箭头
      "\U000F0140",  # mdi-向下箭头
      "\U000F089E",  # mdi-电池
      "\U000F0317",  # mdi-局域网（LAN）
      "\U000F0425",  # mdi-电源
      "\U000F050F",  # mdi-温度计
      ]
  - file: "../fonts/materialdesignicons-webfont.ttf"
    id: icon_font_small
    size: 20
    bpp: 4
    glyphs: [
      "\U000F050F",  # mdi-温度计
      ]

# 将图标映射为易读的名称（用于 YAML 变量替换）
substitutions:
  lightbulb:      "\U000F0335"      # 灯泡
  nightlight:     "\U000F1A4C"      # 夜灯
  network:        "\U000F1087"      # 网络
  application:    "\U000F0614"      # 应用程序
  chevron_left:   "\U000F0141"      # 左箭头
  chevron_up:     "\U000F0143"      # 上箭头
  chevron_down:   "\U000F0140"      # 下箭头
  battery:        "\U000F089E"      # 电池
  lan:            "\U000F0317"      # 局域网
  power:          "\U000F0425"      # 电源
  thermometer:    "\U000F050F"      # 温度计