# xiaomiao
substitutions:
  name: "xiaomiao"
  friendly_name: "xiaomiao-esphome"

# Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# 导入组件
packages:
  device: !include packages/device.yaml
  sensors: !include packages/sensors.yaml
  fonts: !include packages/fonts.yaml
