# xiaomiao
substitutions:
  name: "xiaomiao"
  friendly_name: "xiaomiao-esphome"
  allowed_characters: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz°-_.:,;!?@#$%^&*()[]{}<>/\\|+=~`\"' "

# Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# 导入组件
packages:
  device: !include packages/device.yaml
  sensors: !include packages/sensors.yaml
  fonts: !include packages/fonts.yaml

# 时间同步（需连 Home Assistant）
time:
  - platform: homeassistant
    id: ha_time
    timezone: Asia/Shanghai